# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e8d077899c8f928f9eb46c9480d085385d4221474dd5bd2d11ce75b0099881df9e95e02173a12e11bd2889b3cff853f835fc9a70c55cd9d46da6a25ab898847

test:
  secret_key_base: ea711bc8b22d0f60c33c1a7e14d64c5fa7d26c3df0a327381a499da47fbe8537e9c82f9433156e4ffc6460fd5d702bc474eb5a6688fcffd9d759b219ee31808f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
